<?php
$pageTitle = 'Department of Arts, Commerce & Social Sciences – Dr APJ University Indore';
$bodyClass = 'wp-singular page-template page-template-pages page-template-inner-page page-template-pagesinner-page-php page page-id-1926 wp-custom-logo wp-theme-aku no-sidebar wpb-js-composer js-comp-ver-8.7.2 vc_responsive';
$useLiveReferenceAssets = true;
$activeDepartmentPage = 'arts';
include 'header.php';
?>

<section class="page-header" style="background-image: url('assets/images/bg-header.jpg')">
    <div class="uk-container">
        <h1>Department of Arts, Commerce &amp; Social Sciences</h1>
        <nav class="breadcrumb" aria-label="Breadcrumb"><a href="index.php">Home</a> &raquo; Department of Arts, Commerce &amp; Social Sciences</nav>
    </div>
</section>

<main id="primary" class="site-main">
<article id="post-1926" class="post-1926 page type-page status-publish hentry">
<div class="uk-container"><div class="entry-content"><div class="wpb-content-wrapper">
<div class="vc_row wpb_row vc_row-fluid"><div class="wpb_column vc_column_container vc_col-sm-12"><div class="vc_column-inner"><div class="wpb_wrapper">
<div class="vc_empty_space" style="height:32px"><span class="vc_empty_space_inner"></span></div>
<div class="vc_tta-container" data-vc-action="collapse"><div class="vc_general vc_tta vc_tta-tabs vc_tta-color-grey vc_tta-style-classic vc_tta-shape-rounded vc_tta-spacing-4 vc_tta-tabs-position-left vc_tta-controls-align-left">
<div class="vc_tta-tabs-container"><ul class="vc_tta-tabs-list" role="tablist">
    <li class="vc_tta-tab vc_active" data-vc-tab role="presentation"><a href="#arts-about" data-vc-tabs data-vc-container=".vc_tta" role="tab"><span class="vc_tta-title-text">About the Department</span></a></li>
    <li class="vc_tta-tab" data-vc-tab role="presentation"><a href="#arts-vision" data-vc-tabs data-vc-container=".vc_tta" role="tab"><span class="vc_tta-title-text">Vision &amp; Mission</span></a></li>
    <li class="vc_tta-tab" data-vc-tab role="presentation"><a href="#arts-message" data-vc-tabs data-vc-container=".vc_tta" role="tab"><span class="vc_tta-title-text">Dean/Principal Messege</span></a></li>
    <li class="vc_tta-tab" data-vc-tab role="presentation"><a href="#arts-faculty" data-vc-tabs data-vc-container=".vc_tta" role="tab"><span class="vc_tta-title-text">Faculty &amp; Staff Profile</span></a></li>
    <li class="vc_tta-tab" data-vc-tab role="presentation"><a href="#arts-infrastructure" data-vc-tabs data-vc-container=".vc_tta" role="tab"><span class="vc_tta-title-text">Infrastructure</span></a></li>
    <li class="vc_tta-tab" data-vc-tab role="presentation"><a href="#arts-syllabus" data-vc-tabs data-vc-container=".vc_tta" role="tab"><span class="vc_tta-title-text">Syllabus &amp; Scheme</span></a></li>
    <li class="vc_tta-tab" data-vc-tab role="presentation"><a href="#arts-copo" data-vc-tabs data-vc-container=".vc_tta" role="tab"><span class="vc_tta-title-text">CO/PO</span></a></li>
    <li class="vc_tta-tab" data-vc-tab role="presentation"><a href="#arts-activities" data-vc-tabs data-vc-container=".vc_tta" role="tab"><span class="vc_tta-title-text">Activities</span></a></li>
    <li class="vc_tta-tab" data-vc-tab role="presentation"><a href="#arts-notice" data-vc-tabs data-vc-container=".vc_tta" role="tab"><span class="vc_tta-title-text">Notice Board</span></a></li>
    <li class="vc_tta-tab" data-vc-tab role="presentation"><a href="#arts-events" data-vc-tabs data-vc-container=".vc_tta" role="tab"><span class="vc_tta-title-text">Events and News</span></a></li>
    <li class="vc_tta-tab" data-vc-tab role="presentation"><a href="#arts-timetable" data-vc-tabs data-vc-container=".vc_tta" role="tab"><span class="vc_tta-title-text">Time Table</span></a></li>
</ul></div>

<div class="vc_tta-panels-container"><div class="vc_tta-panels">
<div class="vc_tta-panel vc_active" id="arts-about" data-vc-content=".vc_tta-panel-body">
    <div class="vc_tta-panel-heading"><h4 class="vc_tta-panel-title"><a href="#arts-about" data-vc-accordion data-vc-container=".vc_tta-container"><span class="vc_tta-title-text">About the Department</span></a></h4></div>
    <div class="vc_tta-panel-body"><h2 style="text-align:center" class="vc_custom_heading vc_do_custom_heading">About The Department</h2>
        <div class="vc_row wpb_row vc_inner vc_row-fluid">
            <div class="wpb_column vc_column_container vc_col-sm-6"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="wpb_single_image wpb_content_element vc_align_left department-image"><figure class="wpb_wrapper vc_figure"><div class="vc_single_image-wrapper vc_box_border vc_box_border_grey"><img fetchpriority="high" decoding="async" width="1200" height="800" src="uploads/2026/01/department-of-social-science.jpg" class="vc_single_image-img attachment-full" alt="Department of Arts, Commerce and Social Sciences" title="department-of-social-science"></div></figure></div></div></div></div>
            <div class="wpb_column vc_column_container vc_col-sm-6"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="wpb_text_column wpb_content_element wpb_animate_when_almost_visible wpb_zoomIn zoomIn vision-box"><div class="wpb_wrapper"><p>The <strong>Department of Arts</strong> is dedicated to fostering creativity, critical thinking, and cultural awareness through a broad spectrum of disciplines including Literature, History, Political Science, Sociology, Philosophy, Psychology, and Fine Arts. Our department offers a dynamic academic environment that encourages students to explore human expression, social structures, and intellectual traditions from both contemporary and historical perspectives.</p><p>We aim to develop well-rounded individuals equipped with analytical and communication skills essential for careers in education, civil services, media, public relations, social work, and the creative industries. Through a blend of theoretical knowledge and practical engagement, our programs prepare students to contribute meaningfully to society and pursue lifelong learning.</p></div></div></div></div></div>
        </div>
    </div>
</div>

<div class="vc_tta-panel" id="arts-vision" data-vc-content=".vc_tta-panel-body">
    <div class="vc_tta-panel-heading"><h4 class="vc_tta-panel-title"><a href="#arts-vision" data-vc-accordion data-vc-container=".vc_tta-container"><span class="vc_tta-title-text">Vision &amp; Mission</span></a></h4></div>
    <div class="vc_tta-panel-body"><h2 style="text-align:center" class="vc_custom_heading vc_do_custom_heading">Vision</h2>
        <div class="vc_row wpb_row vc_inner vc_row-fluid"><div class="wpb_column vc_column_container vc_col-sm-3"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="wpb_single_image wpb_content_element vc_align_center"><figure class="wpb_wrapper vc_figure"><div class="vc_single_image-wrapper vc_box_circle vc_box_border_grey"><img decoding="async" width="150" height="150" src="uploads/2025/06/vissio11-150x150.jpg" class="vc_single_image-img attachment-thumbnail" alt="Vision"></div></figure></div></div></div></div><div class="wpb_column vc_column_container vc_col-sm-9"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="wpb_text_column wpb_content_element wpb_animate_when_almost_visible wpb_zoomIn zoomIn vision-box"><div class="wpb_wrapper"><p>To cultivate globally competent architects who blend creativity with responsibility, preserving cultural heritage while promoting sustainable and futuristic design solutions.</p></div></div></div></div></div></div>
        <div class="vc_separator wpb_content_element vc_separator_align_center vc_sep_width_100 vc_sep_pos_align_center vc_separator_no_text vc_sep_color_chino"><span class="vc_sep_holder vc_sep_holder_l"><span class="vc_sep_line"></span></span><span class="vc_sep_holder vc_sep_holder_r"><span class="vc_sep_line"></span></span></div>
        <h2 style="text-align:center" class="vc_custom_heading vc_do_custom_heading">Mission</h2>
        <div class="vc_row wpb_row vc_inner vc_row-fluid"><div class="wpb_column vc_column_container vc_col-sm-3"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="wpb_single_image wpb_content_element vc_align_center"><figure class="wpb_wrapper vc_figure"><div class="vc_single_image-wrapper vc_box_circle vc_box_border_grey"><img decoding="async" width="150" height="150" src="uploads/2025/06/mission11-150x150.jpg" class="vc_single_image-img attachment-thumbnail" alt="Mission"></div></figure></div></div></div></div><div class="wpb_column vc_column_container vc_col-sm-9"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="wpb_text_column wpb_content_element wpb_animate_when_almost_visible wpb_zoomIn zoomIn mission-box"><div class="wpb_wrapper"><ul><li>To provide high-quality education in architectural design, theory, history, and technology.</li><li>To promote sustainable and context-sensitive design practices.</li><li>To encourage research, innovation, and interdisciplinary collaboration.</li><li>To engage students in real-world projects and community-based design initiatives.</li></ul></div></div></div></div></div></div>
    </div>
</div>

<div class="vc_tta-panel" id="arts-message" data-vc-content=".vc_tta-panel-body">
    <div class="vc_tta-panel-heading"><h4 class="vc_tta-panel-title"><a href="#arts-message" data-vc-accordion data-vc-container=".vc_tta-container"><span class="vc_tta-title-text">Dean/Principal Messege</span></a></h4></div>
    <div class="vc_tta-panel-body"><h2 style="text-align:center" class="vc_custom_heading vc_do_custom_heading">Principal Message</h2><div class="wpb_text_column wpb_content_element wpb_animate_when_almost_visible wpb_zoomIn zoomIn"><div class="wpb_wrapper"><p>It gives me immense pleasure to welcome all the students of Under-graduate and Post-graduate courses and Research streams. Campus is Located in the heart of the city. The infrastructure that the college has is second to none. We have a dedicated faculty who open the door for the students but at the same time expect them to enter it by themselves. There is no force more paralyzing than the fear of failure. We mound our students to be self confident and pragmatic such that when they enter life after their studies, they face various challenges with courage, conviction and success.</p><p>The students must exhibit exemplary behavior even outside the college without getting themselves provoked or letting themselves be taken for a ride especially while travelling. Directly or indirectly, knowingly or unknowingly, they should in no way bring disrepute to the college of their study. I am sure our students will always strive to uphold the dignity of our college and keep its flag ever flying high. India is known for its rich values, culture and heritage. I impress upon all our young learning community to emerge as her proud and worthy citizens.</p><p><a href="https://www.aku.ac.in/website/images/21102020_043506_BBA.jpg"><strong>BBA LOGISTICS COURSE :- Apprenticeship-Based BBA Degree Programme in Logistics launched in Dr. A.P.J. Abdul Kalam University, Indore in collaboration with Logistics Sector Skill Council (LSC)</strong></a></p></div></div><div class="wpb_text_column wpb_content_element"><div class="wpb_wrapper"><p style="text-align:right"><strong>Principal COPS</strong></p></div></div></div>
</div>

<div class="vc_tta-panel" id="arts-faculty" data-vc-content=".vc_tta-panel-body">
    <div class="vc_tta-panel-heading"><h4 class="vc_tta-panel-title"><a href="#arts-faculty" data-vc-accordion data-vc-container=".vc_tta-container"><span class="vc_tta-title-text">Faculty &amp; Staff Profile</span></a></h4></div>
    <div class="vc_tta-panel-body"><h2 style="text-align:center" class="vc_custom_heading vc_do_custom_heading">Faculty &amp; Staff</h2>
        <div class="vc_row wpb_row vc_inner vc_row-fluid arts-faculty-grid">
            <div class="wpb_column vc_column_container vc_col-sm-3"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="profile-card"><div class="profile-content"><h4>Chandrapal Singh</h4><p>Professor</p></div></div><div class="profile-card"><div class="profile-content"><h4>Pooja Medam</h4><p>Professor</p></div></div></div></div></div>
            <div class="wpb_column vc_column_container vc_col-sm-3"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="profile-card"><div class="profile-content"><h4>Dr. Anil Malviya</h4><p>Professor</p></div></div><div class="profile-card"><div class="profile-content"><h4>Samreen Qureshi</h4><p>Professor</p></div></div></div></div></div>
            <div class="wpb_column vc_column_container vc_col-sm-3"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="profile-card"><div class="profile-content"><h4>Dr. Aparna Tripati</h4><p>Professor</p></div></div><div class="profile-card"><div class="profile-content"><h4>Murari Choudhary</h4><p>Professor</p></div></div></div></div></div>
            <div class="wpb_column vc_column_container vc_col-sm-3"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="profile-card"><div class="profile-content"><h4>Kishor Choudhary</h4><p>Professor</p></div></div></div></div></div>
        </div>
    </div>
</div>

<div class="vc_tta-panel" id="arts-infrastructure" data-vc-content=".vc_tta-panel-body">
    <div class="vc_tta-panel-heading"><h4 class="vc_tta-panel-title"><a href="#arts-infrastructure" data-vc-accordion data-vc-container=".vc_tta-container"><span class="vc_tta-title-text">Infrastructure</span></a></h4></div>
    <div class="vc_tta-panel-body"><div class="vc_row wpb_row vc_inner vc_row-fluid"><div class="wpb_column vc_column_container vc_col-sm-6"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="wpb_raw_code wpb_raw_html wpb_content_element infra-card"><div class="wpb_wrapper"><img decoding="async" src="uploads/2025/06/classroom.jpg" alt="Modern Classrooms"><h4>Modern classrooms</h4><p>Modern classrooms with smart boards, audio-visual aids, and ergonomic furniture.</p></div></div><div class="wpb_raw_code wpb_raw_html wpb_content_element infra-card"><div class="wpb_wrapper"><img decoding="async" src="uploads/2025/06/library.jpg" alt="Libraries"><h4>Libraries</h4><p>Libraries with massive collections of physical books, journals, and access to global digital databases.</p></div></div></div></div></div><div class="wpb_column vc_column_container vc_col-sm-6"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="wpb_raw_code wpb_raw_html wpb_content_element infra-card"><div class="wpb_wrapper"><img decoding="async" src="uploads/2025/06/1-1.png" alt="Advanced laboratories"><h4>Advanced laboratories</h4><p>Advanced laboratories for various disciplines—science, engineering, medical, etc.</p></div></div><div class="wpb_raw_code wpb_raw_html wpb_content_element infra-card"><div class="wpb_wrapper"><img decoding="async" src="uploads/2025/06/101888.jpg" alt="Wi-Fi Smart Campuses"><h4>Wi-Fi Smart Campuses</h4><p>Wi-Fi enabled smart campuses with seamless digital connectivity. High speed internet.</p></div></div></div></div></div></div></div>
</div>

<div class="vc_tta-panel" id="arts-syllabus" data-vc-content=".vc_tta-panel-body"><div class="vc_tta-panel-heading"><h4 class="vc_tta-panel-title"><a href="#arts-syllabus" data-vc-accordion data-vc-container=".vc_tta-container"><span class="vc_tta-title-text">Syllabus &amp; Scheme</span></a></h4></div><div class="vc_tta-panel-body"><h2 style="text-align:center" class="vc_custom_heading vc_do_custom_heading">Syllabus</h2><div class="vc_message_box vc_message_box-standard vc_message_box-rounded vc_color-info vc_do_message"><div class="vc_message_box-icon"><i class="fa fa-solid fa-circle-info"></i></div><p>No Syllabus</p></div></div></div>
<div class="vc_tta-panel" id="arts-copo" data-vc-content=".vc_tta-panel-body"><div class="vc_tta-panel-heading"><h4 class="vc_tta-panel-title"><a href="#arts-copo" data-vc-accordion data-vc-container=".vc_tta-container"><span class="vc_tta-title-text">CO/PO</span></a></h4></div><div class="vc_tta-panel-body"></div></div>

<div class="vc_tta-panel" id="arts-activities" data-vc-content=".vc_tta-panel-body"><div class="vc_tta-panel-heading"><h4 class="vc_tta-panel-title"><a href="#arts-activities" data-vc-accordion data-vc-container=".vc_tta-container"><span class="vc_tta-title-text">Activities</span></a></h4></div><div class="vc_tta-panel-body"><h2 style="text-align:center" class="vc_custom_heading vc_do_custom_heading">Activities</h2><div class="wpb_text_column wpb_content_element file_page2"><div class="wpb_wrapper"><h2><em>Activities</em></h2><table class="filr-table"><tr><th>Title</th></tr><tr><td><a href="uploads/2025/07/Vist-Report-20.05.2025.pdf" target="_blank">Vist Report 20.05.2025</a></td></tr><tr><td><a href="uploads/2025/07/Skill-Development-Programme.pdf" target="_blank">Skill Development Programme</a></td></tr><tr><td><a href="uploads/2025/07/Dr.-Bhimrao-Ambedkar-Programme.pdf" target="_blank">Dr. Bhimrao Ambedkar Programme</a></td></tr></table></div></div></div></div>

<div class="vc_tta-panel" id="arts-notice" data-vc-content=".vc_tta-panel-body"><div class="vc_tta-panel-heading"><h4 class="vc_tta-panel-title"><a href="#arts-notice" data-vc-accordion data-vc-container=".vc_tta-container"><span class="vc_tta-title-text">Notice Board</span></a></h4></div><div class="vc_tta-panel-body"><div class="vc_message_box vc_message_box-standard vc_message_box-rounded vc_color-info vc_do_message"><div class="vc_message_box-icon"><i class="fa fa-solid fa-circle-info"></i></div><p>Notice Board</p></div></div></div>

<div class="vc_tta-panel" id="arts-events" data-vc-content=".vc_tta-panel-body"><div class="vc_tta-panel-heading"><h4 class="vc_tta-panel-title"><a href="#arts-events" data-vc-accordion data-vc-container=".vc_tta-container"><span class="vc_tta-title-text">Events and News</span></a></h4></div><div class="vc_tta-panel-body"><h2 style="text-align:center" class="vc_custom_heading vc_do_custom_heading">Events &amp; News</h2><div class="wpb_text_column wpb_content_element media-img media-text"><div class="wpb_wrapper"><div class="grid-media"><div class="grid-item"><a href="aku-in-media.php"><img decoding="async" src="assets/images/aajtak_news-300x200.png" alt="AAJ TAK"><p class="text-18">कानून की समझ क्यों जरूरी है ? AAJ TAK</p></a></div><div class="grid-item"><a href="aku-in-media.php"><img decoding="async" src="assets/images/dev_kumawat-e1765884635936-300x200.jpg" alt="देव कुमावत"><p class="text-18">देव कुमावत को वेस्ट जोन बैडमिंटन का एकल खिताब</p></a></div><div class="grid-item"><a href="aku-in-media.php"><img decoding="async" src="assets/images/apja-couselling-300x200.jpg" alt="अंतरराष्ट्रीय सम्मेलन"><p class="text-18">एपीजे अब्दुल कलाम यूनिवर्सिटी में आईपीजीए का अंतरराष्ट्रीय सम्मेलन</p></a></div><div class="grid-item"><a href="aku-in-media.php"><img decoding="async" src="assets/images/u37.jpg" alt="College Level Counselling"><p class="text-18">College Level Counselling</p></a></div></div></div></div></div></div>

<div class="vc_tta-panel" id="arts-timetable" data-vc-content=".vc_tta-panel-body"><div class="vc_tta-panel-heading"><h4 class="vc_tta-panel-title"><a href="#arts-timetable" data-vc-accordion data-vc-container=".vc_tta-container"><span class="vc_tta-title-text">Time Table</span></a></h4></div><div class="vc_tta-panel-body"><h2 style="text-align:center" class="vc_custom_heading vc_do_custom_heading">Time Table</h2><div class="wpb_text_column wpb_content_element file_page2"><div class="wpb_wrapper"><h2><em>Time Table</em></h2><table class="filr-table"><tr><th>Title</th></tr><tr><td><a href="uploads/2025/07/Right-Time-teble-B.A.-II-IV-VI-2025.pdf" target="_blank">Right Time teble B.A. II, IV, VI 2025</a></td></tr><tr><td><a href="uploads/2025/07/B.A.-M.A.-Time-Table.pdf" target="_blank">B.A. + M.A. Time Table</a></td></tr></table></div></div></div></div>
</div></div></div></div>

<div class="vc_row wpb_row vc_row-fluid"><div class="wpb_column vc_column_container vc_col-sm-12"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="wpb_text_column wpb_content_element"><div class="wpb_wrapper">
<style>
.arts-faculty-grid .profile-card{margin-bottom:20px}.courses_heading{padding-bottom:18px;font-size:22px;font-weight:700;color:#222;text-transform:uppercase;letter-spacing:1px;position:relative;text-align:left}.courses_heading span{background:linear-gradient(90deg,#b1001c,#ff4b5c);-webkit-background-clip:text;-webkit-text-fill-color:transparent;font-weight:800}.uk-card.special-course-box{background:linear-gradient(135deg,#fff 0%,#f1f8ff 100%);border-left:4px solid #b1001c;border-radius:12px;transition:all .4s cubic-bezier(.25,.46,.45,.94);padding:20px 25px;margin-bottom:20px;min-height:80px;display:flex;align-items:center;justify-content:center;box-shadow:0 2px 8px rgb(0 0 0 / 10%);position:relative;overflow:hidden}.uk-card.special-course-box:before{content:'';position:absolute;inset:0 auto 0 0;width:0;background-color:rgba(177,0,28,.08);transition:width .4s ease}.uk-card.special-course-box:hover{transform:translateY(-3px);box-shadow:0 6px 16px rgba(0,0,0,.12)}.uk-card.special-course-box:hover:before{width:100%}.uk-card.special-course-box a{text-decoration:none;color:#1d1d1d;font-weight:600;font-size:16px;position:relative;z-index:1}.uk-card.special-course-box:hover a{color:#b1001c}.uk-card.special-course-box a:after{content:'→';margin-left:8px;opacity:0;transition:all .3s ease;display:inline-block;transform:translateX(-5px)}.uk-card.special-course-box:hover a:after{opacity:1;transform:translateX(0)}
</style>
<div class="uk-container uk-margin"><h2 class="vc_custom_heading vc_do_custom_heading" style="text-align:center">Courses</h2>
<div class="uk-margin"><h3 class="uk-heading-line uk-text-primary courses_heading"><span>Under Graduate Programs</span></h3><div class="uk-flex uk-flex-wrap uk-grid-small" uk-grid><div class="uk-width-1-2@s uk-width-1-3@m"><div class="uk-card special-course-box"><a href="course/ba.php">BA (Plain)</a></div></div><div class="uk-width-1-2@s uk-width-1-3@m"><div class="uk-card special-course-box"><a href="course/bsw-bachelor-of-social-work.php">BSW (Bachelor of Social Work)</a></div></div></div></div>
<div class="uk-margin"><h3 class="uk-heading-line uk-text-primary courses_heading"><span>Post Graduation Programs</span></h3><div class="uk-flex uk-flex-wrap uk-grid-small" uk-grid><div class="uk-width-1-2@s uk-width-1-3@m"><div class="uk-card special-course-box"><a href="course/ma-master-of-arts.php">M.A. (English)</a></div></div><div class="uk-width-1-2@s uk-width-1-3@m"><div class="uk-card special-course-box"><a href="course/m-a-geography.php">M.A. (Geography)</a></div></div><div class="uk-width-1-2@s uk-width-1-3@m"><div class="uk-card special-course-box"><a href="course/m-a-hindi.php">M.A. (Hindi)</a></div></div><div class="uk-width-1-2@s uk-width-1-3@m"><div class="uk-card special-course-box"><a href="course/m-a-political-science.php">M.A. (Political Science)</a></div></div><div class="uk-width-1-2@s uk-width-1-3@m"><div class="uk-card special-course-box"><a href="course/m-a-psychology.php">M.A. (Psychology)</a></div></div><div class="uk-width-1-2@s uk-width-1-3@m"><div class="uk-card special-course-box"><a href="course/m-a-sociology.php">M.A. (Sociology)</a></div></div><div class="uk-width-1-2@s uk-width-1-3@m"><div class="uk-card special-course-box"><a href="course/msw-master-of-social-work-2.php">MSW (Master of Social Work)</a></div></div></div></div>
</div></div></div></div></div></div></div>
</div></div></div></article></main>
<?php include 'footer.php'; ?>
